/*
 * This source file was generated by the Gradle 'init' task
 */
package dashboard;

import org.junit.jupiter.api.Test;

import dashboard.App;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {

}
